### ISSUE TITLE
Whitelisting RPA devices with local Random Static Address.

### ISSUE THREAD

**Issue by b14ck-ping** [espressif/esp-nimble#32]
Hello!

I am currently working on a device that should work like this: 
1. The device is invisible to all non-whitelisted devices (filter policy is 3) and have Static Random Address.
2. The process of pairing with a new Central device is started by pressing the button. Pressing the button switches the filtering policy to mode 0.
3. After pairing, the device is added to the whitelist, and the whitelist is saved in non-volatile memory so that when the device is rebooted it can be uploaded to the working whitelist. 

When I connect from my smartphone to the device, the pairing and bonding process is successful. The smartphone reconnects and accepts advertising packages, which means that the whitelist is working. But, unfortunately, when a smartphone changes its RPA address, the pairing process has to be repeated, because for ESP32 the smartphone has become a different device with a different address. 

I went through all the threads in this repository and none helped me.  

I use:
ESP-IDF v4.3.1, and nimble-1.3.0-idf-v4.3-afr.

HW: ESP32-WROOM-32D

nRF Connect on Android 11

In addition my main.c file and log-file.
[main.txt](https://github.com/espressif/esp-nimble/files/7192157/main.txt)
[nimble_periph_Log.txt](https://github.com/espressif/esp-nimble/files/7192158/nimble_periph_Log.txt)

**Comment by b14ck-ping** [comment]
if I change Key Distribution Mask to:

ble_hs_cfg.sm_our_key_dist = BLE_SM_PAIR_KEY_DIST_ENC | BLE_SM_PAIR_KEY_DIST_ID;
ble_hs_cfg.sm_their_key_dist = BLE_SM_PAIR_KEY_DIST_ENC | BLE_SM_PAIR_KEY_DIST_ID;

then I can't roconnect to ESP32 until I clean the bond list on smartphone or reboot ESP32. But when a smartphone changes its RPA address ESP32 still can no longer recognize him by the whitelist.

**Comment by rahult-github** [comment]
Hi @happy-sloth ,

> When I connect from my smartphone to the device, the pairing and bonding process is successful. The smartphone reconnects and accepts advertising packages, which means that the whitelist is working. But, unfortunately, when a smartphone changes its RPA address, the pairing process has to be repeated, because for ESP32 the smartphone has become a different device with a different address. 

For ESP32, it uses Host based privacy, which means address resolution happens at host stack ( and not controller). In this case, the first time the address that was added in whitelist was the same that remote smartphone was advertising. When remote device changes the RPA address, the address now in whitelist is not the same , and controller is not doing any address resolution either. 


> if I change Key Distribution Mask to:
> 
> ble_hs_cfg.sm_our_key_dist = BLE_SM_PAIR_KEY_DIST_ENC | BLE_SM_PAIR_KEY_DIST_ID;
> ble_hs_cfg.sm_their_key_dist = BLE_SM_PAIR_KEY_DIST_ENC | BLE_SM_PAIR_KEY_DIST_ID;
> 
> then I can't roconnect to ESP32 until I clean the bond list on smartphone or reboot ESP32. But when a smartphone changes its RPA address ESP32 still can no longer recognize him by the whitelist.

Can you please share your sdkconfig.txt   and device side logs with DEBUG prints enabled (menuconfig--> Component config --> Log output --> Debug log verbosity to Debug)?)  I can check for more details.



Thanks,
 Rahul

**Comment by b14ck-ping** [comment]
Hi @rahult-github !

I was working on commercial projects and there was a very tight deadline, so I quickly switched to bluedroid and implemented a manual check of the address for presence in the bond list. And completely forgot about my question. Does it make sense to continue this? Because I already forgot what the problem was.

**Comment by rahult-github** [comment]
May be we can close this and you can reopen a new one when you observe the issue .
