### ISSUE TITLE
ble_hs_id_addr() debug assert hit via ble_hs_pvcy_set_default_irk()

### ISSUE THREAD

**Issue by kenh-sq** [espressif/esp-nimble#61]
`BLE_HS_DBG_ASSERT(ble_hs_locked_by_cur_task());` is getting hit within the call to `ble_hs_id_addr()` from `ble_hs_pvcy_set_default_irk()`.

Wrapping the `ble_hs_id_addr()` call with the respective `ble_hs_lock()/ble_hs_unlock()` might be all that's needed?

**Comment by rahult-github** [comment]
Hi @kenh-sq ,  

Recently a fix was made around this  [here](https://github.com/espressif/esp-nimble/commit/3dea93163a66c852d935d040e6ba6cedd5552707)  .  I think this should resolve the issue for you .

**Comment by rahult-github** [comment]
Closing this issue. Please feel free to reopen if issue still persists.
